# Generated by Django 4.2.2 on 2023-06-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiretubers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiretuber',
            name='event_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
