# Generated by Django 3.1.7 on 2021-04-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('fb_link', models.CharField(max_length=150)),
                ('insta_link', models.CharField(max_length=150)),
                ('twt_link', models.CharField(max_length=150)),
                ('yt_link', models.CharField(max_length=150)),
            ],
        ),
    ]
