# Generated by Django 4.2.2 on 2023-08-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_slider_event_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='fb_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='insta_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='websiteinfo',
            name='fb_link',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='websiteinfo',
            name='insta_link',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='websiteinfo',
            name='twt_link',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='websiteinfo',
            name='yt_link',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
