# Generated by Django 3.1.7 on 2021-03-19 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youtuber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(upload_to='media/ytubers/%Y/%m/')),
                ('video_url', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('camera_type', models.CharField(max_length=250)),
                ('subs_count', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_date', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
