# Generated by Django 3.1.7 on 2021-03-19 15:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('solo', 'solo'), ('small', 'small'), ('large', 'large')], default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('canon', 'Canon'), ('nikon', 'Nikon'), ('sony', 'Sony'), ('red', 'Red'), ('fuji', 'Fuji'), ('panasonic', 'Panasonic'), ('other', 'Other')], max_length=250),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('coder', 'Coder'), ('tech', 'Tech'), ('vlogs', 'Vlogs'), ('comedy', 'Comedy'), ('gamer', 'Gamer'), ('film_making', 'Film_Making'), ('cooking', 'Cooking'), ('other', 'Other')], max_length=250),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
