# Generated by Django 3.1.7 on 2021-03-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_auto_20210319_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='youtuber',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('canon', 'Canon'), ('nikon', 'Nikon'), ('sony', 'Sony'), ('red', 'Red'), ('fuji', 'Fuji'), ('panasonic', 'Panasonic'), ('Gopro', 'Gopro'), ('other', 'Other')], max_length=250),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('coder', 'Coder'), ('tech', 'Tech'), ('vlogs', 'Vlogs'), ('comedy', 'Comedy'), ('gamer', 'Gamer'), ('film_making', 'Film_Making'), ('food', 'food'), ('other', 'Other')], max_length=250),
        ),
    ]
